# github repository Actions 페이지에 나타낼 이름
name: CI/CD

# event trigger
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
          submodules: true
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Execute Gradle build
        run: ./gradlew clean build -x test -Pprofile=growith #application 프로필 이름
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: build and release to DockerHub
        env:
          NAME: ${{secrets.DOCKER_USER}}
          APP: growith
        run: |
          docker build -t $NAME/$APP -f ./Dockerfile .
          docker push $NAME/$APP:latest
      - name: EC2 Docker Run
        run: |
          ssh -i ${{secrets.EC2_KEY}} root@${{secrets.EC2_HOST}} 'cd /root/compose && \
            docker-compose down --rmi all && \
            docker pull ${{secrets.DOCKER_USER}}/growith:latest && \
            docker-compose up -d'